sudo: required
language: java
services:
  - docker
env:
  global:
  - GIT_USERNAME=Travis CI
  - GIT_EMAIL=builds@travis-ci.com
  - TAG=$(./pipeline.sh getProperty version gradle.properties)
  - RELEASE_FILE=build/libs/encryptor-api-$TAG.jar
  - RELEASE_POM=build/pom.xml
  - LAST_COMMIT_MESSAGE=$(git log -1 --pretty=%B | tr -d '\n')
  - CD_COMMIT_MESSAGE='[travis] Bump version number'
  - GITHUB_USER=dermotmburke
  - DOCKER_USERNAME=buildittravis
  - secure: TCNj3xF353ATWTWmMOBk41rRsGQU2ID76PXG9KIqeW0YO5u7PU48fIGin2q44wET71vMp2PuDOT0Bi3fkAfVjGTWBjRdrJOyV/vmEhDbW2W+rF9SNazbYqKtyERhOYL8EhsbTJXC17XmaU3GHtTzD+l32jUDm5CNHvX71FDBlCGIIJc2phCkhUNHcAvTnPRtxeu3CCtd1pU7wgPL6LB5ztgrWAbb5z9a7mfVZ8XVR1Y9e46U3197SYlvz81tsDjwjfcgst4MrEkCWg2XskcZ91RzBFrdJBY/x9o2S+nCpyIuxLeBjZMg8+DjMTTpaBQqbsVkkFtcoTiiTFKQTFNloSxtdxlDwbR1ErbyKj9QBs6h30qUUDU3xoBLUynSzhOqBwiusSQtUXxRjlbFWBRjgmRLcisqGe9xAv4xCA6GdP7IiTuN+VKfS0sv1NvNVo3XyKGlPr2b8yOrYKCszhqx9LzduAdqa88bjZwAwh6eoD6EkHG2GwIHPwaNs+J8sOEvhWzQl3N0xyA4ycdYP86opaHnwDU6KOJr+a6yn+4X8ffrOdpRGgGQ6oaKXV5BN+MtoZwKwXru+uf7BbVZ2K6hR+SpKCN+SxCR8sBx7Fui0IZPNVaotvDvyB95b9IYdYzzIv97hpFNxpl7rjq9Do/YPOeiuGpBIinIFwvZApcKJZs=
  - secure: kHO+rBRobo8ZaL0ANIkUWJTCOWIkycZgzjbNFD8C9570yCfKIjodbI3gB42N72Dhw13v+J08p9zrKBkFSi8Am50kpDZKfXwE/qFthgGNThNFpMmje8jPR8N3JCp36seT2QtUVfkc486grw57/JduId4Uzas3WevR2kbZ/OykjsCoOk5/ajVx1mFZrG/NziSENwkHSDQv4TM86M3jaMFghteIUuWcAxmucF45VI4QDltmTXbbJaoJQuVlCGL9awm+JvoRG41WgDlczAWDWufYAZFrtzwuxsEb08ojmrLlFnaDnhqPyTPPkhmwyy5X5JufMewikZayuzSodh2upCTRckSn21M64SCun19I6yRO6BSPKPmj2Ng+eaMH8hRVcstk0Y+nmdjOrOCBv88atA4OPgwAHPp7ZkVCuf76GPg6hV+sUf8Ij+To3HWsYxJe3TMgfb1NJ/Jgk85yqVAImkQXHHmEKswZa5hdOEBD5lqxHms/YUFTZ1u0sPrvaYVAhQHuwZajUH0tvWiLdzWc1T1JGb06vUUIvwmL2h0ZXSFiV2mE7/7uAyx0jDC5LTon420Q7cVQx7HQLKCKAOsehhrpFw/C1Qv2+V84aKs7rbXgJzIqCZfZ7YoTOXrp5ydKwmbCMSZtv01XYcQKsO/ttTd3+YPmh6esfQWHgYFwZkzLn6M=
  - secure: Q1qeJ/as+2eRDaZgra5M9f/E55KEtp28CiTyZtsa0t+CH1h6dN8+Kf8F4hd4FMJNQj+Xa/+xGbjBeQHsRCZnBy1a0TKPdeLS909e1etO2rSiJ8MuR/Zn/1T1J4O07WxTomoZH3vuFETNrmWBwXyHpAQLYx0yBRyaUM5V7Pt2+IWPYiqChnSmh0ZU4cuPx6rYvs/QhfXq1W4a2b/ZwcXL0p4+zcnefkbXeZ21iy1IW7M/OhLrJxSExyRhy9oY1GCCLCSFITjOtA5Ke7aiFO8Du/CYO0tYKHHV+x29TMpyk+3buIHSYQGXlIDFHVcFWFjX5/JTdmMjhw3/lUK/e/EuqIQ1EOq4vNP/e/OeFbdjoOl26IQ4x2A3iwGzW85YBh2+B+KoaNdB7E0trS5tFUaJLz9UILg6PKixTUoRQW9gRC7T29pxsfvK7D5WEeWtP/eXkr1QQg6YiIsKcH0LhVnJhlrCVNWN6XrULmwrRHXwFrSy3Y2ISEV4wz6bUcIwF0k0DCUZR6Vsfa9B6h2W0z6C99EEd230wK8cZfVofBWLfYrVqfe+Lh0p/wDugk/ywV6a0bifH/+Pj6w4HjLLB+XtLBMGRaQKR/zzlqroCS+pxvRaWDBDixqcjnRqvm+4lDaOIuLMtBVJnKsHWqAlU/XTL2jcpzosTVA5REkbLfsOxAk=
script:
- ./pipeline.sh build
before_deploy:
- ./pipeline.sh tag
- ./pipeline.sh dockerLogin
deploy:
  - provider: script
    script: gradle bintrayUpload -PbintrayUser=buildit -PbintrayKey=$BINTRAY_TOKEN -PdryRun=false buildDocker
    skip_cleanup: true
    on:
      branch: master
      tags: false
      condition: '"${LAST_COMMIT_MESSAGE}" != "${CD_COMMIT_MESSAGE}"'
after_deploy:
- ./pipeline.sh bump